/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as AccomodationRouteImport } from './routes/accomodation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccomodationDetailRouteImport } from './routes/accomodation_.detail'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccomodationRoute = AccomodationRouteImport.update({
  id: '/accomodation',
  path: '/accomodation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccomodationDetailRoute = AccomodationDetailRouteImport.update({
  id: '/accomodation_/detail',
  path: '/accomodation/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accomodation': typeof AccomodationRoute
  '/cms': typeof CmsRoute
  '/login': typeof LoginRoute
  '/accomodation/detail': typeof AccomodationDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accomodation': typeof AccomodationRoute
  '/cms': typeof CmsRoute
  '/login': typeof LoginRoute
  '/accomodation/detail': typeof AccomodationDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accomodation': typeof AccomodationRoute
  '/cms': typeof CmsRoute
  '/login': typeof LoginRoute
  '/accomodation_/detail': typeof AccomodationDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accomodation' | '/cms' | '/login' | '/accomodation/detail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accomodation' | '/cms' | '/login' | '/accomodation/detail'
  id:
    | '__root__'
    | '/'
    | '/accomodation'
    | '/cms'
    | '/login'
    | '/accomodation_/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccomodationRoute: typeof AccomodationRoute
  CmsRoute: typeof CmsRoute
  LoginRoute: typeof LoginRoute
  AccomodationDetailRoute: typeof AccomodationDetailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accomodation': {
      id: '/accomodation'
      path: '/accomodation'
      fullPath: '/accomodation'
      preLoaderRoute: typeof AccomodationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accomodation_/detail': {
      id: '/accomodation_/detail'
      path: '/accomodation/detail'
      fullPath: '/accomodation/detail'
      preLoaderRoute: typeof AccomodationDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccomodationRoute: AccomodationRoute,
  CmsRoute: CmsRoute,
  LoginRoute: LoginRoute,
  AccomodationDetailRoute: AccomodationDetailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
